# Generated by Django 4.1.7 on 2023-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[(0, "Fall"), (1, "Spring"), (2, "Summer")],
                        default=1,
                        max_length=9,
                    ),
                ),
                ("year", models.IntegerField()),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "db_table": "semester",
                "unique_together": {("term", "year")},
            },
        ),
    ]
