# Generated by Django 4.1.7 on 2023-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=1000),
        ),
    ]
