# Generated by Django 4.1.7 on 2023-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
