# Generated by Django 4.1.7 on 2023-04-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('D', 'Draft'), ('R', 'Rejected')], default='active', max_length=10),
        ),
    ]
