# Generated by Django 4.1.7 on 2023-04-20 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester_course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_term', models.IntegerField()),
                ('final', models.IntegerField()),
                ('semester_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester_course.semestercourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester Course Student',
                'verbose_name_plural': 'Semester Course Students',
                'db_table': 'semester_course_student',
            },
        ),
    ]
