# Generated by Django 4.1.7 on 2023-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semester_course_student", "0002_semestercoursestudent_make_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semestercoursestudent",
            name="final",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semestercoursestudent",
            name="mid_term",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
