# Generated by Django 4.1.7 on 2023-04-25 09:48

from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('semester_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester_course.semestercourse')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report',
            },
        ),
    ]
