# Generated by Django 4.1.7 on 2023-05-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        ('group_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('version', models.IntegerField()),
                ('plagiarism_file', models.FileField(blank=True, null=True, upload_to='')),
                ('plagiarism_rate', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_project.groupproject')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
            options={
                'verbose_name': 'Project Report',
                'verbose_name_plural': 'Project Report',
                'db_table': 'project_report',
                'unique_together': {('project', 'report', 'version')},
            },
        ),
    ]
